# Path to your oh-my-zsh installation.
export ZSH=$HOME/.files/zsh

source $ZSH/antigen/antigen.zsh

antigen use oh-my-zsh

# User configuration
# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle heroku
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found
antigen bundle zsh-users/zsh-completions
# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-autosuggestions
# Load the theme.
antigen-theme halfo/lambda-mod-zsh-theme lambda-mod

antigen apply

source $HOME/.files/zsh/z.sh

export TERM="xterm-256color"
export LANG="en_IN.utf8"
export LC_CTYPE="en_IN.UTF-8"
