# Path to your oh-my-zsh installation.
export ZSH=$HOME/dotfiles/zsh

source $ZSH/antigen/antigen.zsh

antigen use oh-my-zsh

# User configuration
# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle heroku
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme.
antigen theme agnoster

antigen apply
