# Path to your oh-my-zsh installation.
export ZSH=$HOME/.files/zsh

source $ZSH/antigen/antigen.zsh

antigen use oh-my-zsh

# User configuration
# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle heroku
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found
antigen bundle zsh-users/zsh-completions
# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme.
antigen-theme halfo/lambda-mod-zsh-theme lambda-mod

antigen apply

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

export NVM_DIR="/home/arkokoley/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
export TERM="xterm-256color"
export LANG="en_IN.utf8"
export LC_CTYPE="en_IN.UTF-8"
